### ISSUE TITLE
[ask] differences in this library with decoder from google maps

### ISSUE THREAD

**Issue by ekarudianto** [mapbox/polyline#12]
I've seen this library and just wondering what the differences this library has with the one that google maps has ?

in my knowledge, you could just decode the encoded path using

```javascript
google.maps.geometry.encoding.decodePath(param)
```

right ?

**Comment by morganherlocker** [comment]
> in my knowledge, you could just decode the encoded path using

`polyline` is a small, independent module with zero dependencies. Unlike `encoding.decodePath`, it can be used in non-visual applications and with other map libraries, such as [Leaflet](http://leafletjs.com/) & [Mapbox.js](https://www.mapbox.com/mapbox.js/api/).
