### ISSUE TITLE
when install it down-version "six"

### ISSUE THREAD

**Issue by zhuobao** [mapbox/polyline#16]
system: centos 7
python: Python 3.5.0 :: Anaconda 2.4.0 (64-bit)

when install, it down-version "six" from 1.10.0 to 1.8.0
below is the log
##################################
$pip install polyline
Collecting polyline
  Downloading polyline-1.1.tar.gz
Collecting six==1.8.0 (from polyline)
  Downloading six-1.8.0-py2.py3-none-any.whl
Building wheels for collected packages: polyline
  Running setup.py bdist_wheel for polyline ... done
  Stored in directory: /home/vzj182/.cache/pip/wheels/d9/d8/f4/2ccd2aecef798e84458df1b30a49e17cd7d6dcb937ff8abbd8
Successfully built polyline
Installing collected packages: six, polyline
  Found existing installation: six 1.10.0
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.10.0:
      Successfully uninstalled six-1.10.0
Successfully installed polyline-1.1 six-1.8.0
########################################

by the way, I manually re-upgrade "six" and polyline worked fine for importing and decoding.

**Comment by jfirebaugh** [comment]
Sorry, I think you have the wrong repository. This repository is for a javascript module, not a python module.
