### ISSUE TITLE
Classic static API can't decode Directions v5 paths

### ISSUE THREAD

**Issue by danswick** [mapbox/polyline#20]
A user reported a strange response from the classic static API and it looks like this may have something to do with the way directions v5 polylines are encoded. 

Here is the user's request: 

https://api.mapbox.com/directions/v5/mapbox/driving/-123.483547,45.938412;-122.92893,46.125485?geometries=polyline&access_token=pk.eyJ1IjoiZGxva29zIiwiYSI6ImVNRmpySFEifQ.D2fZF5erdf_oN_fYjj4C8A

Which returns this encoded polyline: 

```
ajkwGd{tpVeNwt@sp@iEyLwv@X_p@l[_n@Bm`@ukAwwAag@_M}\\wm@agAcZkWie@yG}wCb`@a\\rKkcB`[i]sFgh@{nAixAk|@}`@yYq}Am{@eWt@c|B`l@}q@dMeu@}Cs|@pg@caAaa@axAa^qDeq@f^_v@ub@s~@zj@qc@wFqbArz@iPzi@i`@wEw[r\\wNyUkw@hAdCaOkKwGgh@fIsfAuK_J_MjDscAicAsyAcRgu@tHaiAjOiBoEmWf[wo@oFsaE~T{_@zf@stEaP}lBdK}qAqD}wAqYcxBbV}{HqZ_cB|KytB~Ras@wfCezBb@a`C}k@uWaM~Y
```

The route should look like: 

![image](https://cloud.githubusercontent.com/assets/2365503/16858990/0b1307d2-49e0-11e6-895f-6777c20aac0c.png)

When you plug the above polyline into the classic static api ([request](http://api.mapbox.com/v4/mapbox.streets/path%28ajkwGd%7btpVeNwt%40sp%40iEyLwv%40X_p%40l%5b_n%40Bm%60%40ukAwwAag%40_M%7d%5c%5cwm%40agAcZkWie%40yG%7dwCb%60%40a%5c%5crKkcB%60%5bi%5dsFgh%40%7bnAixAk%7c%40%7d%60%40yYq%7dAm%7b%40eWt%40c%7cB%60l%40%7dq%40dMeu%40%7dCs%7c%40pg%40caAaa%40axAa%5eqDeq%40f%5e_v%40ub%40s~%40zj%40qc%40wFqbArz%40iPzi%40i%60%40wEw%5br%5c%5cwNyUkw%40hAdCaOkKwGgh%40fIsfAuK_J_MjDscAicAsyAcRgu%40tHaiAjOiBoEmWf%5bwo%40oFsaE~T%7b_%40zf%40stEaP%7dlBdK%7dqAqD%7dwAqYcxBbV%7d%7bHqZ_cB%7cKytB~Ras%40wfCezBb%40a%60C%7dk%40uWaM~Y%29/auto/600x600@2x.png?access_token=pk.eyJ1IjoiZGFuc3dpY2siLCJhIjoieUZiWmwtVSJ9.0cPQywdbPVmvHiHJ6NwdXA)), you get the following:

![image](https://cloud.githubusercontent.com/assets/2365503/16859058/9c908d9c-49e0-11e6-87be-5cd2121eaeb7.png)

Which resembles the original geometry, but with a couple of wrong turns. @yhahn noted that this could have something to do with escaped backslashes being removed from the encoded polyline. He also noted that directions v5 encodes polylines with a lower precision than directions v4, which is likely contributing to the issue. 

cc @colleenmcginnis

**Comment by jfirebaugh** [comment]
In JSON, literal backslashes in strings must be escaped with another backslash, so the double backslashes that you see in the response are part of the JSON encoding of the polyline, not part of the polyline itself. The polyline itself is

```
ajkwGd{tpVeNwt@sp@iEyLwv@X_p@l[_n@Bm`@ukAwwAag@_M}\wm@agAcZkWie@yG}wCb`@a\rKkcB`[i]sFgh@{nAixAk|@}`@yYq}Am{@eWt@c|B`l@}q@dMeu@}Cs|@pg@caAaa@axAa^qDeq@f^_v@ub@s~@zj@qc@wFqbArz@iPzi@i`@wEw[r\wNyUkw@hAdCaOkKwGgh@fIsfAuK_J_MjDscAicAsyAcRgu@tHaiAjOiBoEmWf[wo@oFsaE~T{_@zf@stEaP}lBdK}qAqD}wAqYcxBbV}{HqZ_cB|KytB~Ras@wfCezBb@a`C}k@uWaM~Y
```

And [this](http://api.mapbox.com/v4/mapbox.streets/path(ajkwGd%7BtpVeNwt%40sp%40iEyLwv%40X_p%40l%5B_n%40Bm%60%40ukAwwAag%40_M%7D%5Cwm%40agAcZkWie%40yG%7DwCb%60%40a%5CrKkcB%60%5Bi%5DsFgh%40%7BnAixAk%7C%40%7D%60%40yYq%7DAm%7B%40eWt%40c%7CB%60l%40%7Dq%40dMeu%40%7DCs%7C%40pg%40caAaa%40axAa%5EqDeq%40f%5E_v%40ub%40s~%40zj%40qc%40wFqbArz%40iPzi%40i%60%40wEw%5Br%5CwNyUkw%40hAdCaOkKwGgh%40fIsfAuK_J_MjDscAicAsyAcRgu%40tHaiAjOiBoEmWf%5Bwo%40oFsaE~T%7B_%40zf%40stEaP%7DlBdK%7DqAqD%7DwAqYcxBbV%7D%7BHqZ_cB%7CKytB~Ras%40wfCezBb%40a%60C%7Dk%40uWaM~Y)/auto/600x600@2x.png?access_token=pk.eyJ1IjoiZGFuc3dpY2siLCJhIjoieUZiWmwtVSJ9.0cPQywdbPVmvHiHJ6NwdXA) is the correct static URL, which works as expected.
