### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by sandstrom** [mapbox/polyline#22]
There has been a bunch of updates, but the most recent release (0.2) is from [august 2015](https://github.com/mapbox/polyline/tree/d55f84a6279f00e84d6a09ad2e0da7d6e745dc4b).

A new release would be awesome! ⛵️

**Comment by jfirebaugh** [comment]
The most recent release is https://www.npmjs.com/package/@mapbox/polyline, from December 2016, and has all the changes in the repository as of right now.

**Comment by sandstrom** [comment]
Thanks for answering @jfirebaugh! Much appreciated!

What do you think about adding timestamps + version details to the [changelog](https://github.com/mapbox/polyline/blob/master/CHANGELOG.md)?

Plus a bump to the version number (according to the cited npm page the lastest version is still 0.2, but that one is from august 2015 according to the git history in this repo).

![image](https://cloud.githubusercontent.com/assets/122287/25172724/308230a4-24f2-11e7-8837-fe6acd82738d.png)
