### ISSUE TITLE
Decoded polyline needs escaping of '/' chars

### ISSUE THREAD

**Issue by n8ores** [mapbox/polyline#23]
Decoding the following Encoded polyline yields incorrect data (A number of lat,lng pairs were missing)

`z``mEm~zv[rNgaALmc@kFg~AMae@zV_gCZqR{y@}F_u@wJ_^_DkN{@cHrkBfd@znA_X|uCsReBcF|j@{fAo\cNsOwIaBqJnFwIge@rFgeAyrBaTsHvdAyJa@cFtj@}GQxt@fhCq@zQp@tEpDxEg@pCP`DFvDgA|CiYza@sBrSaS~XM`G_A`DiM`QwBbHOnFmBtS~PnCiKhqAn{@_A`eAtHdtAfYhf@mEtGeGb[_k@zA_o@aKwm@nKg`@rRsGl\fJvQxJz@uDhCsEpIyChCoB|E{OcF}C@oIfDiTnBcQlCqYlAkHnOe_@jJc^`

I discovered I could recover the missing [lat,lngs] by double escaping the '\\' characters. The complete and correct encoded polyline becomes:

`z``mEm~zv[rNgaALmc@kFg~AMae@zV_gCZqR{y@}F_u@wJ_^_DkN{@cHrkBfd@znA_X|uCsReBcF|j@{fAo\\cNsOwIaBqJnFwIge@rFgeAyrBaTsHvdAyJa@cFtj@}GQxt@fhCq@zQp@tEpDxEg@pCP`DFvDgA|CiYza@sBrSaS~XM`G_A`DiM`QwBbHOnFmBtS~PnCiKhqAn{@_A`eAtHdtAfYhf@mEtGeGb[_k@zA_o@aKwm@nKg`@rRsGl\\fJvQxJz@uDhCsEpIyChCoB|E{OcF}C@oIfDiTnBcQlCqYlAkHnOe_@jJc^`

**Comment by jfirebaugh** [comment]
Are you passing this data in a double-quote delimited string? If so, yes, you'll need to escape `\`. That's not a polyline requirement though, that's just JavaScript syntax.

**Comment by n8ores** [comment]
I was passing it as a single quote string e.g 'ASDFASDFASD' yes.

I didn't think you could call polyline.decode(AQSADFASFDASD) as the input argument surely has to be a string?

**Comment by jfirebaugh** [comment]
Sorry, my comment was a bit imprecise -- "string literal" was what I meant to say. What you're seeing is the same as this:

```
console.log('\t'); // prints a tab character
console.log('\\t'); // prints a backslash character followed by a 't' character
```

This isn't anything specific to polyline, it's just how string literals in JavaScript work.

**Comment by n8ores** [comment]
Yes but presumably encoded polylines will very often contain a \ character. 

Having to remember to escape these characters to use the polyline.decode() method is a bit silly. If someone passes a string containing a \ e.g polyline.decode("abcd\fasdw?") the polyline.decode method should automatically escape the \ and return the correct data, not rely on the programmer to hunt out each slash and escape it manually.

**Comment by jfirebaugh** [comment]
You're conflating or confusing the in-memory representation of a string with representation of a string literal in source code text. polyline operates on in-memory string representation, where there is no notion of escaping, and no need to escape special characters. You only need to escape "manually" if you are passing polyline data as a string literal which is hard-coded into the JavaScript source. In most cases, you pass a polyline string obtained from some other web service or data source.

**Comment by n8ores** [comment]
I was calling polyline.decode() manually from the NPM console (following one of many suggestions found online for decoding polylines). 

So yes, while you are technically correct there is still a use case where someone runs polyline.decode('xy/z') directly from the NPM console and it will omit numerous pairs of points.
