### ISSUE TITLE
npm install doesn't install @mapbox

### ISSUE THREAD

**Issue by valinsky** [mapbox/polyline#26]
Scenario - after cloning my repo and running npm install, this is the only package not being installed. after manually running npm install @mapbox/polyline it works just fine.

`Module does not exist in the module map or in these directories: /path/to/MyReactNativeProject/node_modules/@mapbox``

Cheers

**Comment by jfirebaugh** [comment]
This is very likely an issue with npm and not specific to polyline. Please make sure you're running a recent version of npm, as older versions did not support organizations (`@mapbox` prefix).
