### ISSUE TITLE
Swap lat & long so is consistent with Mapbox Map coordinate

### ISSUE THREAD

**Issue by Altiano** [mapbox/polyline#27]
Swap lat & long so is consistent with Mapbox Map coordinate

**Comment by jfirebaugh** [comment]
[Every choice for coordinate order is inconsistent with some library or convention.](https://macwright.org/lonlat/) This library has made its choice and won't be changing, sorry.

**Comment by Altiano** [comment]
well, it just weird that mapbox gl js use lng lat and this library use otherwise. I think at least make it consistent with mapbox gl js

**Comment by huevosabio** [comment]
I second this. If the purpose is to transform Google Maps encoding to be used in Mapbox ecosystem, then it should return objects with the same convention as the target ecosystem.

**Comment by winseyli** [comment]
Agree
