### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by sandstrom** [mapbox/polyline#33]
There has been many nice additions, but the version still stand at 0.2.0.

Awesome if you could mint a new release to npm. 💯

**Comment by jfirebaugh** [comment]
There's nothing in `master` that's not in 0.2.0. https://www.npmjs.com/package/@mapbox/polyline

**Comment by sandstrom** [comment]
Please help me understand. It was published 10 months ago and there are many commits on master.

This [diff shows a fix for the rounding error](https://github.com/mapbox/polyline/compare/d55f84a6279f00e84d6a09ad2e0da7d6e745dc4b...master), among other things.

**Comment by jfirebaugh** [comment]
@sandstrom Are you using the `@mapbox/polyline` package?

**Comment by sandstrom** [comment]
@jfirebaugh Yes you are right!

I got confused by the changelog which shows [no changes since 2015](https://github.com/mapbox/polyline/blob/master/CHANGELOG.md).

I've made a PR with some adjustments: https://github.com/mapbox/polyline/pull/34
