### ISSUE TITLE
TypeError: undefined is not an object

### ISSUE THREAD

**Issue by aceramos** [mapbox/polyline#36]
TypeError: undefined is not an object (evaluating 'respJson.routes[0].overview_polyline')

This thing pops up when the route is not available, where can i edit this alert or completely remove it ? please help.

**Comment by lbud** [comment]
Hey @aceramos, it sounds like this might be an application-specific issue, not an issue with encoding and decoding a polyline. If I'm incorrect in this and you are finding an error produced by the polyline module, please provide a minimal reproducible example ([jsfiddle](https://jsfiddle.net/) or the like) so we can diagnose it.
