### ISSUE TITLE
coordinates twisted in commandline mode

### ISSUE THREAD

**Issue by jtheuer** [mapbox/polyline#37]
This should return the coordinates in the opposite order (is: `lat,lng` should be `lng,lat` because geojson expects the data in `x,y` order.)

```
# source data order is lat=51, lng=10
$> echo "_}gvH_c`|@_ibE_ibE" | polyline --decode
[[51,10],[52,11],[51.99994,11]]
```

Version: ```@mapbox/polyline@0.2.0```

**Comment by jfirebaugh** [comment]
As per the README, encoding and decoding uses [lat, lng] order, since that's the polyline algorithm's native convention. But I have just added a `--toGeoJSON` option that will output a GeoJSON LineString with GeoJSON's [lng, lat] order.

**Comment by jtheuer** [comment]
Awesome, thanks for the quick improvement!

It took me a while to find out what you mean by "As per README ..." since I was looking at the command line documentation but then I found the code comment you mean!
