### ISSUE TITLE
No tag or release for v1.0.0

### ISSUE THREAD

**Issue by morgant** [mapbox/polyline#39]
I see that `@mapbox/polyline` shows as [v1.0.0 in `npm`](https://www.npmjs.com/package/@mapbox/polyline) and I see the related commits ((54aeca2)[https://github.com/mapbox/polyline/commit/54aeca247d2fb81b237006666067be798b4b9689] through (eaa1f05)[https://github.com/mapbox/polyline/commit/eaa1f056a908fdf275f1d966070d3decd23c0483]) from 2018-04-01, but there's no tag or release on the project. It's helpful to have these, esp. for those who might not be using Node or aren't paying attention to commit details.

**Comment by badrange** [comment]
That would indeed be helpful!

**Comment by tristen** [comment]
👍 Apologies for the delay. `1.1.0` has been tagged and released https://github.com/mapbox/polyline/releases/tag/1.1.0. Closing.
