### ISSUE TITLE
import for angular?

### ISSUE THREAD

**Issue by Raven5650** [mapbox/polyline#48]
is there an option for importing it in angular with the import keyword instead of require?

**Comment by michaelbats** [comment]
import & as polyline from '@mapbox/polyline' 

I'm using it and works fine.

**Comment by andrewharvey** [comment]
closing per previous comment which should address this, but if not please post back.

**Comment by csimpi** [comment]
@sebastiangug can you specify how exactly should I import it to Angular 9? Thank you

**Comment by sebastiangug** [comment]
import * as polyline from "@mapbox/polyline"

**Comment by csimpi** [comment]
@sebastiangug Worked, thank you!
