### ISSUE TITLE
timestamp support

### ISSUE THREAD

**Issue by GopherJ** [mapbox/polyline#50]

**Comment by GopherJ** [comment]
It's important to know the when do we get this geo position, is it possible to timestamp into the string? I know that the algo may doesn't have this support~

**Comment by lyzidiamond** [comment]
An encoded polyline only contains the `geometry` of a feature. Note that your result is not a full GeoJSON feature, just the `geometry` object. This is expected behavior!

**Comment by GopherJ** [comment]
ok
