### ISSUE TITLE
npm audit issue (meow > yargs-parser)

### ISSUE THREAD

**Issue by dmytro-gokun** [mapbox/polyline#63]
The current version depends on "meow": "^5.0.0", which in turn depends on "yargs-parser": "^10.0.0". And that one has a known audit issue: https://www.npmjs.com/advisories/1500.

The solution would be to update meow to ^6.1.1 (https://github.com/sindresorhus/meow/releases/tag/v6.1.1) which has this issue fixed.

**Comment by andrewharvey** [comment]
closed by #68
