### ISSUE TITLE
Deafults return wrong coordinates with OSRM results

### ISSUE THREAD

**Issue by apollolm** [mapbox/polyline#9]
Hitting the OSRM endpoint: 

    https://router.project-osrm.org/viaroute?z=15&output=json&loc=47.603832,-122.330062&loc=47.097946,-122.424342&instructions=true,

and then using `polyline.decode(route_geometry); ` returns and array of coords that look like this:

    0: 472.10022
    1: -1224.33977

Being in Seattle, I recognized that these are 1 decimal off.  Setting the precision to 6 like this:
    
    polyline.decode(route_geometry, [6]);

Does the trick.  

    0: 47.210022
    1: -122.433977

Seems like the default should do that?  Or did I miss something?

Thanks!

**Comment by jfirebaugh** [comment]
The polyline default of precision 5 was chosen to match the precision of Google polylines. But as you noticed, OSRM has chosen to use a higher precision. So yes, when using polyline with OSRM, you have to specify 6.
